### PR TITLE
[BACKLOG-7093] - Upgrade Mongo version to latest (3.2)

### PR DESCRIPTION
**Pull request by stepanovdg**

### CODE REVIEW

**Comment by stepanovdg** [comment]
linked with https://github.com/pentaho/pentaho-mongo-utils/pull/50

**Comment by stepanovdg** [comment]
@brosander Could you please take a look?

**Comment by lucboudreau** [comment]
http://10.100.11.222:8080/job/wingman/15/

**Comment by lucboudreau** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Build Sensitive Files Changed:
==============================
  pom.xml

Changed files:
==============
  pom.xml
  src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInput.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutput.java
  src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputTest.java
  src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputTest.java



Unit test coverage change:
============
org.pentaho.di.trans.steps.mongodbinput.MongoDbInput:
 * Branch Change :  + .28%
 * Complexity Change :  + .81%
 * Instruction Change :  + 1.23%
 * Line Change :  + 1.52%

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutput:
 * Branch Change :  + 3.41%
 * Complexity Change :  + 4.90%
 * Instruction Change :  + 3.64%
 * Line Change :  + 3.74%

**Comment by brosander** [comment]
@stepanovdg why the reduced logging and retry logic? is that handled by the driver now?

**Comment by lucboudreau** [comment]
+1 on Bryan's comment. Please restore the logging.

**Comment by stepanovdg** [comment]
According to documentation and spike results ( http://jira.pentaho.com/browse/BACKLOG-6430 ) - curently there is no ability to get info about which server was used (getServerUsed() method and functionality were fully removed ) - so that`s why detailed logging with servers info was removed.
Also at new version there is no need to directly call getLastError() and extract error message from the received result. Now any dbCollection manipulation methods will throw usual MongoException in case of any fail.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  pom.xml
  src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInput.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutput.java
  src/test/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputTest.java
  src/test/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputTest.java

Unit test coverage change:
============
org.pentaho.di.trans.steps.mongodbinput.MongoDbInput:
 * Branch Change :  + .28%
 * Complexity Change :  + .81%
 * Instruction Change :  + 1.23%
 * Line Change :  + 1.52%

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutput:
 * Branch Change :  + 3.56%
 * Complexity Change :  + 5.11%
 * Instruction Change :  + 3.64%
 * Line Change :  + 3.74%

**Comment by dkincade** [comment]
I am going to merge this request along with the other related requests. I know that some of the IT are not passing in this area but those need to be removed to automated QA tests and not run as Integration Tests due to their required configuration.

**Pull request merged**
