### PR TITLE
[SP-6555] Update and validate in-product links in Pentaho 9.3.0.8

### PR DESCRIPTION
**Pull request by eddie-martinez**

### CODE REVIEW

**Comment by buildguy** [comment]
### :warning: Build finished in 2m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox -pl \
pentaho-mongodb-plugin
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputTest.testStepMetaSettingUpsertAlsoSetsUpdateInXML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputTest.testStepMetaSetsUpdateInXML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **109**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-mongodb-plugin-jdk11/job/PR-235/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
<div align='center'>

[👍 Frogbot scanned this pull request and found that it did not add vulnerable dependencies.](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

<details>
<summary> <b>Note:</b> </summary>


---
<div align='center'>

**Frogbot** also supports **Contextual Analysis, Secret Detection, IaC and SAST Vulnerabilities Scanning**. This features are included as part of the [JFrog Advanced Security](https://jfrog.com/advanced-security) package, which isn't enabled on your system.

</div>


</details>


---
<div align='center'>

[🐸 JFrog Frogbot](https://docs.jfrog-applications.jfrog.io/jfrog-applications/frogbot)

</div>

**Comment by buildguy** [comment]
### :warning: Build finished in 4m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -Djs.no.sandbox
```
---
### :no_entry: Failed Tests

#### :cloud_with_lightning_and_rain: 2 test(s) failed:

<details><summary><b>org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputTest.testStepMetaSettingUpsertAlsoSetsUpdateInXML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

<details><summary><b>org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputTest.testStepMetaSetsUpdateInXML</b> (click to expand)</summary><p>

```
${result.errorDetails}
```

</p></details>

  
Tests run: **109**, Failures: **2**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/big-data-mongodb-plugin-jdk11/job/PR-235/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by smmribeiro — APPROVED** [review]
Consistent with the original PR [pentaho-mongodb-plugin#231](https://github.com/pentaho/pentaho-mongodb-plugin/pull/231) (failed unit tests seem unrelated)

**Pull request merged**
