### PR TITLE
[PDI-19187] Remove MongoDB steps from OSGi/Karaf, and place it as a r…

### PR DESCRIPTION
**Pull request by syamkumar-karri**
…egular /plugins plugin

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 6s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **106**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-mongodb-plugin/job/PR-208/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 6m 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **106**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-mongodb-plugin/job/PR-208/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 9s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Review by peterrinehart — COMMENTED** [review]
Please see comments; these are minor/cleanup.  Great work.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 3m 31s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **106**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-mongodb-plugin/job/PR-208/4/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 2m 14s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **106**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](http://wingman.pentaho.net/job/projects/job/big-data-mongodb-plugin/job/PR-208/5/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by peterrinehart** [comment]
PR 209 supersedes this one.

**Pull request closed without merging**
