### PR TITLE
[BACKLOG-8784] - Not correct format for osgi import-package for mongodb-plugin, fix for pom

### PR DESCRIPTION
**Pull request by VasilinaTerehova**
new dependency for osgi plugin was added in commit 3fc4c8ba6315e6714d756bf04c29c5383fdeb34c
resolution:=optional,javax.crypto.spec*;
the format should be javax.crypto.spec*;resolution:=optional,
the issue comes to error while executing maven-bundle-plugin and came to error starting bundle on ce server

### CODE REVIEW

**Comment by vasilina-terehova-epam** [comment]
@dkincade Could you please take a view?

**Comment by dkincade** [comment]
I would really want @rmansoor or @pentaho-nbaker to review...

**Comment by VasilinaTerehova** [comment]
@dkincade could you please provide more details for test failure - locally no failure happens, also there is no enough stacktrace to figure out what of object is null - it can be in parent class BaseMetadataInjectionTest setup method - but no additional information - what line is shown, just part of stacktrace(only for MongoDbOutputMetaInjectionTest) is inserted by wingman

**Comment by dkincade** [comment]
@VasilinaTerehova Please update the license header in MongoDbInputDataTest.java to have the year of 2016. I will then review the information about the unit tests to see if we can include this.

**Comment by VasilinaTerehova** [comment]
@dkincade that changes are only to understand what fails in wingman, so I already found the reason and the fix - very soon will squash commits, only one with needed changes remains.
The reason was that static field LOG field used in BeanInjectionInfo, created from factory KettleLogStore.getLogChannelInterfaceFactory() couldn't be instantiated when wingman run, so I gave mock to factory and set factory to kettle
I will give one more comment and fix everything

**Comment by VasilinaTerehova** [comment]
@dkincade done, tests fixed, code cleaned, commits squashed :) 
https://github.com/pentaho/pentaho-mongodb-plugin/pull/128/commits/ee88d1a2380299064a266af6b6becf33881305eb - the same changes in pom from Nick Hudak

**Pull request merged**
