### PR TITLE
[PDI-15038] - Support MongoDB AuthenticationDatabase Parameter in MongoDB Steps and Support the SCRAM-SHA-1 security

### PR DESCRIPTION
**Pull request by eliofreitas**

### CODE REVIEW

**Comment by eliofreitas** [comment]
requires: pentaho/pentaho-karaf-assembly#191
requires: https://github.com/pentaho/pentaho-mongo-utils/pull/51

**Comment by eliofreitas** [comment]
@pamval please review

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Build Sensitive Files Changed:
==============================
  pom.xml

Changed files:
==============
  .gitignore
  pom.xml
  src/main/java/org/pentaho/di/trans/steps/mongodb/MongoDbMeta.java
  src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java
  src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java
  src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java
  src/main/resources/org/pentaho/di/trans/steps/mongodbinput/messages/messages_en_US.properties
  src/main/resources/org/pentaho/di/trans/steps/mongodboutput/messages/messages_en_US.properties

Unit test coverage change:
============
org.pentaho.di.trans.steps.mongodb.MongoDbMeta:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.mongodbinput.MongoDbInput:
 * Branch Change : **-61.63%**
 * Complexity Change : **-38.78%**
 * Instruction Change : **-82.68%**
 * Line Change : **-83.21%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.mongodbinput.MongoDbInputData:
 * Branch Change : **-81.67%**
 * Complexity Change : **-75.61%**
 * Instruction Change : **-91.98%**
 * Line Change : **-93.91%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.mongodbinput.MongoDbInputDiscoverFieldsHolder:
 * Branch Change : **-71.43%**
 * Complexity Change : **-69.23%**
 * Instruction Change : **-83.12%**
 * Line Change : **-92.50%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.mongodbinput.MongoDbInputMeta:
 * Branch Change : **-53.75%**
 * Complexity Change : **-47.14%**
 * Instruction Change : **-87.43%**
 * Line Change : **-86.51%**
 * Method Change : **-83.33%**

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutput:
 * Branch Change : **-59.15%**
 * Complexity Change : **-38.55%**
 * Instruction Change : **-70.15%**
 * Line Change : **-72.34%**
 * Method Change : **-91.67%**

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputData:
 * Branch Change : **-65.17%**
 * Complexity Change : **-52.12%**
 * Instruction Change : **-77.61%**
 * Line Change : **-78.75%**
 * Method Change : **-95.00%**

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputData.MongoTopLevel:
 * Complexity Change : **-50.00%**
 * Instruction Change : **-81.25%**
 * Line Change : **-100.00%**
 * Method Change : **-50.00%**

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputMeta:
 * Branch Change : **-62.50%**
 * Complexity Change : **-50.00%**
 * Instruction Change : **-91.11%**
 * Line Change : **-89.80%**
 * Method Change : **-81.25%**

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputMeta.MongoField:
 * Branch Change : **-80.00%**
 * Complexity Change : **-77.78%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputMeta.MongoIndex:
 * Complexity Change : **-100.00%**
 * Instruction Change : **-100.00%**
 * Line Change : **-100.00%**
 * Method Change : **-100.00%**

org.pentaho.di.ui.trans.steps.mongodbinput.MongoDbInputDialog:
 * Branch Change : **-5.33%**
 * Complexity Change : **-7.07%**
 * Instruction Change : **-2.50%**
 * Line Change : **-3.49%**
 * Method Change : **-12.50%**

org.pentaho.di.ui.trans.steps.mongodbinput.MongoDbInputDialog.new DiscoverFieldsCallback() {...}:
 * Branch Change : **-50.00%**
 * Complexity Change : **-75.00%**
 * Instruction Change : **-69.23%**
 * Line Change : **-83.33%**
 * Method Change : **-100.00%**

org.pentaho.mongo.wrapper.field.MongoArrayExpansion:
 * Branch Change : **-51.67%**
 * Complexity Change : **-37.84%**
 * Instruction Change : **-61.11%**
 * Line Change : **-60.42%**
 * Method Change : **-85.71%**

org.pentaho.mongo.wrapper.field.MongodbInputDiscoverFieldsImpl:
 * Branch Change : **-75.00%**
 * Complexity Change : **-59.15%**
 * Instruction Change : **-90.07%**
 * Line Change : **-90.48%**
 * Method Change : **-92.31%**

org.pentaho.mongo.wrapper.field.MongodbInputDiscoverFieldsImpl.new MongoDBAction() {...}:
 * Branch Change : **-62.50%**
 * Complexity Change : **-42.86%**
 * Instruction Change : **-75.00%**
 * Line Change : **-83.33%**
 * Method Change : **-100.00%**

org.pentaho.mongo.wrapper.field.MongoField:
 * Branch Change : **-65.91%**
 * Complexity Change : **-58.62%**
 * Instruction Change : **-77.57%**
 * Line Change : **-80.88%**
 * Method Change : **-100.00%**

org.pentaho.mongo.wrapper.KettleMongoUtilLogger:
 * Branch Change : **-50.00%**
 * Complexity Change : **-54.55%**
 * Instruction Change : **-95.92%**
 * Line Change : **-94.44%**
 * Method Change : **-100.00%**

org.pentaho.mongo.wrapper.MongoWrapperUtil:
 * Branch Change : **-90.00%**
 * Complexity Change : **-84.62%**
 * Instruction Change : **-98.32%**
 * Line Change : **-97.50%**
 * Method Change : **-87.50%**

org.pentaho.mongo.wrapper.MongoWrapperUtil.new MongoWrapperClientFactory() {...}:
 * Complexity Change : **-50.00%**
 * Instruction Change : **-42.86%**
 * Line Change : **-50.00%**
 * Method Change : **-50.00%**

null

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  .gitignore
  pom.xml
  src/main/java/org/pentaho/di/trans/steps/mongodb/MongoDbMeta.java
  src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java
  src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java
  src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java
  src/main/resources/org/pentaho/di/trans/steps/mongodbinput/messages/messages_en_US.properties
  src/main/resources/org/pentaho/di/trans/steps/mongodboutput/messages/messages_en_US.properties

Unit test coverage change:
============
org.pentaho.di.trans.steps.mongodbinput.MongoDbInputMeta:
 * Instruction Change :  + .27%
 * Line Change :  + .26%

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputMeta:
 * Branch Change :  + .89%
 * Instruction Change : **-.02%**
 * Line Change : **-.39%**

org.pentaho.di.ui.trans.steps.mongodbinput.MongoDbInputDialog:
 * Instruction Change : **-.05%**
 * Line Change : **-.07%**

org.pentaho.mongo.wrapper.MongoWrapperUtil:
 * Instruction Change :  + .05%
 * Line Change :  + .06%

null

License header violations:
==========================
1. Copyright year is not the current year on src/main/java/org/pentaho/di/trans/steps/mongodb/MongoDbMeta.java. Found 2015. Was expecting 2016
2. Copyright year is not the current year on src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java. Found 2013. Was expecting 2016
3. Copyright year is not the current year on src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java. Found 2015. Was expecting 2016
4. Copyright year is not the current year on src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java. Found 2015. Was expecting 2016
5. Copyright year is not the current year on src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java. Found 2013. Was expecting 2016
6. Copyright year is not the current year on src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java. Found 2015. Was expecting 2016

**Comment by eliofreitas** [comment]
@pamval ill fix it

**Comment by pamval** [comment]
@eliofreitas please review code style.

**Comment by brosander** [comment]
Build Commands:
==============
Build:
------
1. mvn -B -fn -DrunITs=true -f pom.xml clean install && mvn -B -Dpentaho-coding-standards.version=1.0.4 -f pom.xml site

Cleanup:
-------
mvn -B build-helper:remove-project-artifact

Changed files:
==============
  .gitignore
  pom.xml
  src/main/java/org/pentaho/di/trans/steps/mongodb/MongoDbMeta.java
  src/main/java/org/pentaho/di/trans/steps/mongodbinput/MongoDbInputMeta.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputDialog.java
  src/main/java/org/pentaho/di/trans/steps/mongodboutput/MongoDbOutputMeta.java
  src/main/java/org/pentaho/di/ui/trans/steps/mongodbinput/MongoDbInputDialog.java
  src/main/java/org/pentaho/mongo/wrapper/MongoWrapperUtil.java
  src/main/resources/org/pentaho/di/trans/steps/mongodbinput/messages/messages_en_US.properties
  src/main/resources/org/pentaho/di/trans/steps/mongodboutput/messages/messages_en_US.properties

Unit test coverage change:
============
org.pentaho.di.trans.steps.mongodbinput.MongoDbInputMeta:
 * Instruction Change :  + .27%
 * Line Change :  + .26%

org.pentaho.di.trans.steps.mongodboutput.MongoDbOutputMeta:
 * Instruction Change : **-.02%**
 * Line Change : **-.11%**

org.pentaho.di.ui.trans.steps.mongodbinput.MongoDbInputDialog:
 * Instruction Change : **-.05%**
 * Line Change : **-.07%**

org.pentaho.mongo.wrapper.MongoWrapperUtil:
 * Instruction Change :  + .05%
 * Line Change :  + .06%

null

**Comment by eliofreitas** [comment]
@pamval updated

**Pull request merged**
